version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - errorlint
    - gomodguard
    - gosec
  settings:
    gomodguard:
      blocked:
        modules:
          - github.com/Azure/go-autorest/autorest/azure/auth:
              reason: deprecated
    gosec:
      confidence: low
      config:
        global:
          audit: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
