---
name: "azure-tpl"
version: "0.53.0"
usage: "applies azure information into your helm files"
description: |-
  see https://github.com/webdevops/helm-azure-tpl/blob/main/README.md
ignoreFlags: false
platformCommand:
  ###########################
  # Linux
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/helm-azure-tpl.linux.amd64"
  - os: linux
    arch: arm64
    command: "$HELM_PLUGIN_DIR/helm-azure-tpl.linux.arm64"
  ###########################
  # osx
  - os: darwin
    arch: amd64
    command: "$HELM_PLUGIN_DIR/helm-azure-tpl.darwin.amd64"
  - os: darwin
    arch: arm64
    command: "$HELM_PLUGIN_DIR/helm-azure-tpl.darwin.arm64"
  ###########################
  # Windows
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR/helm-azure-tpl.windows.amd64.exe"
  - os: windows
    arch: arm64
    command: "$HELM_PLUGIN_DIR/helm-azure-tpl.windows.arm64.exe"
hooks:
  install: "bash $HELM_PLUGIN_DIR/plugin/hooks/helm-plugin-install.sh"
  update: "bash $HELM_PLUGIN_DIR/plugin/hooks/helm-plugin-install.sh"

downloaders:
  - command: "plugin/hooks/helm-downloader.sh"
    protocols:
      - "azuretpl"
      - "azure-tpl"
