name: 'Setup-Runner'
description: 'Setup runner'
runs:
  using: composite
  steps:
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@fc79b3f67fa8a838184ce84a674ca12238d2c761
      with:
        swap-size-gb: 12
