name: "release/docker"

on:
  push:
    branches:
      - 'main'
      - 'feature-**'
      - 'bugfix-**'
    tags:
      - '*.*.*'

jobs:
  release:
    uses: ./.github/workflows/build-docker.yaml
    secrets: inherit

