name: "release/docker"

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
      - 'feature-**'
      - 'bugfix-**'
    tags:
      - '*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/build-docker.yaml
    secrets: inherit
    with:
      publish: ${{ github.event_name != 'pull_request' }}
